# Generated by Django 4.2.7 on 2023-11-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('Group', '0002_comment_user_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='groups', to='users.hobbyuser'),
        ),
    ]
