# Generated by Django 4.2.7 on 2023-11-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0003_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='backGround',
            field=models.ImageField(default='defult.jpg', null=True, upload_to='Group_pic'),
        ),
    ]
