# Generated by Django 4.2.6 on 2023-11-01 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hobby', '0002_alter_hobby_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='Hobby.category'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='image',
            field=models.ImageField(null=True, upload_to='Hobby_pic'),
        ),
    ]
