# Generated by Django 4.2.7 on 2023-11-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hobby', '0004_alter_hobby_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default='defult.jpg', null=True, upload_to='Category_pic'),
        ),
    ]
