# Generated by Django 4.2.7 on 2023-11-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hobby', '0004_alter_hobby_image'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbyuser',
            name='hobbies',
            field=models.ManyToManyField(blank=True, to='Hobby.hobby'),
        ),
    ]
