# Generated by Django 4.2.7 on 2023-11-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hobby', '0004_alter_hobby_image'),
        ('users', '0002_hobbyuser_hobbies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbyuser',
            name='hobbies',
            field=models.ManyToManyField(blank=True, related_name='users', to='Hobby.hobby'),
        ),
    ]
